### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Lws0530** [JeffVu-1/Valorant-A.I-Aimbot#1]
where is UserMouseManufacturer 
i can't found

**Comment by Lws0530** [comment]
sorry i don't know how spoofed arduino 
i found the boards.txt

**Comment by Lws0530** [comment]
I've been searching for this for a long time, but it still prompts me that it's not correct. I don't know how to modify it

**Comment by Lws0530** [comment]
My mouse is GPW2. I filled in these information, but it prompted me that it is incorrect

**Comment by JeffVu-1** [comment]
> I've been searching for this for a long time, but it still prompts me that it's not correct. I don't know how to modify it

There's an unknowncheats forum that teaches you how to make the Arduino undetected, 
https://www.unknowncheats.me/forum/valorant/641022-arduino-ud.html

When you spoof your Arduino the cheat needs a way to detect the mouse (when I say mouse I mean Arduino) . So to do that you'd have to update the Mouse.txt file from my cheat with your fake mouse (spoofed Arduino). And you can get your spoofed Arduino's information from "https://the-sz.com/products/temple/".
![Screenshot 2024-11-27 082501](https://github.com/user-attachments/assets/e80f6265-3b02-40d7-ba40-0db0d267e129)
![Screenshot 2024-11-27 082509](https://github.com/user-attachments/assets/372cf771-ffd9-463d-aeca-d1c2553b690f)

**Comment by Lws0530** [comment]
I'm sorry, could you please show me a screenshot of the modifications you made to the usbcore.cpp file? I'm not sure how to make the changes

**Comment by Lws0530** [comment]
D_DEVICE(0xEF,0x02,0x01,64,USB_VID,USB_PID,0x100,IMANUFACTURER,IPRODUCT,ISERIAL,1); 
Should I directly change the content to numerical values here, or is there another way to do it？

**Comment by JeffVu-1** [comment]
> D_DEVICE(0xEF,0x02,0x01,64,USB_VID,USB_PID,0x100,IMANUFACTURER,IPRODUCT,ISERIAL,1); Should I directly change the content to numerical values here, or is there another way to do it？

Yea just follow the UnknownCheats guide, you can change it by simply replacing the hex values with your mouse's hex values. (Personally though when I spoofed my Arduino, I never had that guide. So I can't speak for that guide. However it does seem to cover pretty much everything)

Also when you reach the step of the "external power supply", I'd just purchase a "USBTINY" to Upload/Flash the Arduino, doing it this way will remove the boot loader permanently and saves the headache of having to power the Arduino for 10 seconds with an external power brick. Because if you don't flash it with the USBTINY, then you have to do this every time you restart your pc or unplug your Arduino.

**Comment by Lws0530** [comment]
![微信截图_20241127232453](https://github.com/user-attachments/assets/cbf83941-4412-42bf-8966-54756ea2409d)
![微信截图_20241127232505](https://github.com/user-attachments/assets/10b2508c-d1b1-4bf8-a483-9e3a2c0bd4b2)
I'm really sorry to bother you again. Please help me check why it still shows that the mouse cannot be found after I filled it in this way.

**Comment by JeffVu-1** [comment]
> ![微信截图_20241127232453](https://private-user-images.githubusercontent.com/70701609/390470646-cbf83941-4412-42bf-8966-54756ea2409d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MjUyMDUsIm5iZiI6MTczMjcyNDkwNSwicGF0aCI6Ii83MDcwMTYwOS8zOTA0NzA2NDYtY2JmODM5NDEtNDQxMi00MmJmLTg5NjYtNTQ3NTZlYTI0MDlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDE2MjgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2YTBiNjk5NmVmMzdkNTMyODFkYjIwZTIwMzQzNzhlZTg1YWY5MjBmYmZhOGE2MzUxZTI1YzExODcyYzBjODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ciyJ4ftBiCXUiC7pumsPdGnvt6K--AiWTGf1emAcBaY) ![微信截图_20241127232505](https://private-user-images.githubusercontent.com/70701609/390470667-10b2508c-d1b1-4bf8-a483-9e3a2c0bd4b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MjUyMDUsIm5iZiI6MTczMjcyNDkwNSwicGF0aCI6Ii83MDcwMTYwOS8zOTA0NzA2NjctMTBiMjUwOGMtZDFiMS00YmY4LWE0ODMtOWUzYTJjMGJkNGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDE2MjgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwOTU0ZjlhMWJmODAyZjI5NDMwZjg0NzY3MDZiN2JkMzJlYzQ4YTUwYjMwYzZkYjkwYmE4Mzk4Y2E1ZDI0MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZP7O2rRFqb40636N35r5fNn7yebkzNb4-Y7D8AsWR-U) I'm really sorry to bother you again. Please help me check why it still shows that the mouse cannot be found after I filled it in this way.

idk why you're filling the information inside the actual settings.py grab the actual information from temple.exe and put it inside mouse.txt, you shouldn't have to change anything inside settings.py. You have to find your spoofed Arduino from temple.exe, you can't assume those are the correct values, as you never know what windows recognizes the device as. 

Can you send me the screenshot of Where you're spoofed arduino is in temple.exe, and send me the entire width of it if you can.

**Comment by Lws0530** [comment]
LIGHTSPEED Receiver 	Unknown-Logitech-HIDGD	Logitech, Inc. [0x046D]	USB Receiver [0xC547]	Full Speed - USB 1.1 [12Mb/s], Port: 4, Address: 7, Revision: 0x0100	USB\VID_046D&PID_C547\HIDGD
![Uploading 微信截图_20241128003637.png…]()

**Comment by JeffVu-1** [comment]
I can't see the image you just posted for some reason... but from the text above it should be like the below, However the issue is the manufacture string I can't really tell if it's "LIGHTSPEED Receiver Unknown" or it's just "Unknown". Try resending the image with a link from imgur.

update your mouse.txt like this
vid=0x046D
pid=0xC547
manufacturer_string=LIGHTSPEED Receiver Unknown
serial=HIDGD

**Comment by Lws0530** [comment]
Hello, I'm really sorry for bothering you again. Please help me check this issue
![微信截图_20241210221501](https://github.com/user-attachments/assets/8ccfdccc-1b1e-4dee-b0a6-0f2919084e52)

**Comment by JeffVu-1** [comment]
> Hello, I'm really sorry for bothering you again. Please help me check this issue ![微信截图_20241210221501](https://private-user-images.githubusercontent.com/70701609/394309590-8ccfdccc-1b1e-4dee-b0a6-0f2919084e52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4NDMzMjYsIm5iZiI6MTczMzg0MzAyNiwicGF0aCI6Ii83MDcwMTYwOS8zOTQzMDk1OTAtOGNjZmRjY2MtMWIxZS00ZGVlLWIwYTYtMGYyOTE5MDg0ZTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDE1MDM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNDA3MmM2ZjQzYThiNmY0NDM5MGUyMWNiZGFhOWRmMzJhNmE3NWRiMmNlMjZlNzRiYTZiNGMyMzdhNjgxNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZZSon4RCyU48MFR1a2S4rowpy3lue51Sp0lFdS_3580)

not entirely sure what's going on, try hard encoding the "best.engine" file path into the settings.py.
I don't know if it could be python 3.11 causing issues. 
also i don't know what your main.py looks like, I'm assuming you removed the keyauth, but I don't know if you closed the scope properly.

**Comment by Lws0530** [comment]
The problem has not been resolved
![微信截图_20241210230910](https://github.com/user-attachments/assets/5e233970-0282-4c3e-9593-e92a5a2dc27a)
![微信截图_20241210230921](https://github.com/user-attachments/assets/19f11e29-27b8-4c35-9aab-9617a70d069b)

**Comment by Lws0530** [comment]
okay
